/** Cross-language value parity: every number/string in reference-1.0.json
 * (generated by the Python sibling) must match this implementation.
 * This is THE parity gate for the 1.0 API. */
import { describe, it, expect } from 'vitest';
import { Helmlab } from '../src/index.js';
import ref from './reference/reference-1.0.json';

const hl = new Helmlab();

// Global max-diff tracker so the report shows the worst case per category.
const worst: Record<string, number> = {};
function track(cat: string, diff: number) {
  worst[cat] = Math.max(worst[cat] ?? 0, diff);
}
function close(cat: string, actual: number, expected: number, tol: number) {
  const d = Math.abs(actual - expected);
  track(cat, d);
  expect(d, `${cat}: |${actual} - ${expected}| = ${d}`).toBeLessThanOrEqual(tol);
}
function labClose(cat: string, actual: readonly number[], expected: number[], tol: number) {
  for (let i = 0; i < 3; i++) close(cat, actual[i], expected[i], tol);
}

const LAB_TOL = 5e-9;     // NC LUT PCHIP float ordering differences
const DIST_TOL = 1e-9;
const CUSP_TOL = 2e-3;    // golden-section refinement fp-order sensitivity (C at 1e-4 tol internally)

describe('1.0 cross-language parity (Python-generated reference)', () => {
  it('conversions: labs, lch, hex, p3, rec2020', () => {
    for (const c of ref.conversions) {
      labClose('gen_lab', hl.gen.fromHex(c.color), c.gen_lab, LAB_TOL);
      labClose('gen_lch', hl.gen.toLch(hl.gen.fromHex(c.color)), c.gen_lch, LAB_TOL);
      expect(hl.gen.toHex(hl.gen.fromHex(c.color))).toBe(c.gen_hex);
      expect(hl.gen.toCss(hl.gen.fromHex(c.color), 'display-p3')).toBe(c.gen_p3);
      labClose('metric_lab', hl.metric.fromHex(c.color), c.metric_lab, LAB_TOL);
      const mlch = hl.metric.toLch(hl.metric.fromHex(c.color));
      close('metric_lch', mlch[0], c.metric_lch[0], LAB_TOL);
      close('metric_lch', mlch[1], c.metric_lch[1], LAB_TOL);
      close('metric_lch_H', mlch[2], c.metric_lch[2], mlch[1] > 1e-3 ? 1e-6 : 1e-2);
      expect(hl.metric.toHex(hl.metric.fromHex(c.color))).toBe(c.metric_hex);
      expect(hl.metric.toCss(hl.metric.fromHex(c.color), 'display-p3')).toBe(c.metric_p3);
      expect(hl.metric.toCss(hl.metric.fromHex(c.color), 'rec2020')).toBe(c.metric_rec2020);
    }
  });

  it('gradients + mix: exact string equality', () => {
    for (const g of ref.gradients) {
      expect(hl.gen.gradient(g.a, g.b, 8)).toEqual(g.srgb);
      expect(hl.gen.gradient(g.a, g.b, 8, { gamut: 'display-p3' })).toEqual(g.p3);
      expect(hl.gen.mix(g.a, g.b, 0.25)).toBe(g.mix25);
      expect(hl.gen.mix(g.a, g.b, 0.5)).toBe(g.mix50);
      expect(hl.gen.mix(g.a, g.b, 0.75)).toBe(g.mix75);
    }
  });

  it('palette / scale / hueRing / harmonies / rotate: exact', () => {
    expect(hl.gen.palette('#3b82f6', 10)).toEqual(ref.palette);
    expect(hl.gen.scale('#3b82f6')).toEqual(ref.scale);
    expect(hl.gen.scale('#3b82f6', undefined, { gamut: 'display-p3' })).toEqual(ref.scale_p3);
    expect(hl.gen.hueRing(12)).toEqual(ref.hue_ring);
    for (const [kind, val] of Object.entries(ref.harmonies)) {
      expect(hl.gen.harmonies('#3b82f6', kind as never)).toEqual(val);
    }
    for (const [deg, val] of Object.entries(ref.rotate)) {
      expect(hl.gen.rotateHue('#3b82f6', Number(deg))).toBe(val);
    }
  });

  it('vivid: exact strings', () => {
    for (const v of ref.vivid) {
      expect(hl.gen.vivid(v.c)).toBe(v.srgb);
      expect(hl.gen.vivid(v.c, { gamut: 'display-p3' })).toBe(v.p3);
    }
  });

  it('cusp + maxChroma', () => {
    for (const c of ref.cusp) {
      const s = hl.gen.cusp(c.h);
      const p = hl.gen.cusp(c.h, 'display-p3');
      close('cusp_L', s[0], c.srgb[0], CUSP_TOL);
      close('cusp_C', s[1], c.srgb[1], CUSP_TOL);
      close('cusp_L', p[0], c.p3[0], CUSP_TOL);
      close('cusp_C', p[1], c.p3[1], CUSP_TOL);
      close('maxChroma', hl.gen.maxChroma(0.6, c.h), c.maxC06, 5e-4);
      close('maxChroma', hl.gen.maxChroma(0.6, c.h, 'display-p3'), c.maxC06_p3, 5e-4);
    }
  });

  it('adaptive gamut map', () => {
    const inputs: [number, number, number][] = [[0.5, 0.8, 0.0], [0.9, 0.1, 0.3], [0.2, -0.4, -0.4], [0.95, 0.0, 0.5]];
    inputs.forEach((lab, i) => {
      labClose('adaptive', hl.gen.gamutMap(hl.gen.lab(...lab), 'srgb', 'adaptive'), ref.gamut_map_adaptive[i], 2e-3);
    });
  });

  it('contrast / adapt: exact', () => {
    for (const c of ref.contrast) {
      close('contrast_ratio', hl.gen.contrastRatio(c.fg, c.bg), c.ratio, 1e-9);
      expect(hl.gen.ensureContrast(c.fg, c.bg, 4.5)).toBe(c.fixed);
    }
    for (const a of ref.adapt) expect(hl.gen.adaptToMode(a.c, 'light', 'dark')).toBe(a.dark);
    expect(hl.gen.adaptPair('#333333', '#ffffff', 'light', 'dark', 4.5)).toEqual(ref.adapt_pair);
  });

  it('metrics: difference/euclidean/ciede2000/jnd/distance', () => {
    for (const m of ref.metrics) {
      close('difference', hl.metric.difference(m.a, m.b), m.difference, DIST_TOL);
      close('euclidean', hl.metric.euclidean(m.a, m.b), m.euclidean, DIST_TOL);
      close('ciede2000', hl.metric.ciede2000(m.a, m.b), m.ciede2000, 1e-9);
      close('jnd', hl.metric.jnd(m.a, m.b), m.jnd, 1e-7);
      close('distance', hl.metric.distance(hl.metric.fromHex(m.a), hl.metric.fromHex(m.b)), m.distance, DIST_TOL);
    }
  });

  it('confidence fields', () => {
    for (const c of ref.confidence) {
      const r = hl.metric.confidence(c.a, c.b);
      close('confidence', r.de, c.de, DIST_TOL);
      close('confidence', r.latent, c.latent, 1e-7);
      close('confidence', r.disagreement, c.disagreement, 1e-9);
      close('confidence', r.reliability, c.reliability, 1e-8);
      close('confidence', r.pNoticeable, c.p_noticeable, 1e-7);
      expect(r.reliable).toBe(c.reliable);
      expect(r.extrapolated).toBe(c.extrapolated);
    }
  });

  it('nearest', () => {
    const n = hl.metric.nearest('#3b82f6', ['#3b7ff0', '#ff0000', '#00ff00', '#4c8af7']);
    expect(n.hex).toBe(ref.nearest.hex);
    expect(n.index).toBe(ref.nearest.index);
    close('nearest', n.distance, ref.nearest.distance, 1e-9);
    close('nearest', n.margin, ref.nearest.margin, 1e-6);
  });

  it('info fields incl. wide-gamut inputs', () => {
    for (const i of ref.info) {
      const r = hl.metric.info(i.color);
      expect(r.hex).toBe(i.hex);
      close('info', r.L, i.L, LAB_TOL);
      close('info', r.C, i.C, LAB_TOL);
      // Hue angle of a near-achromatic color is atan2 of numerical noise —
      // a 1e-13 diff in a,b amplifies to ~1e-3 degrees when C ≈ 0.
      close('info_H', r.H, i.H, i.C > 1e-3 ? 1e-6 : 1e-2);
      close('info', r.luminance, i.luminance, 1e-9);
      expect(r.inSrgb).toBe(i.in_srgb);
      expect(r.inP3).toBe(i.in_p3);
      expect(r.inRec2020).toBe(i.in_rec2020);
    }
  });

  it('tokens: exact strings', () => {
    for (const t of ref.tokens) {
      for (const f of ['hex', 'rgb', 'hsl', 'oklch', 'p3', 'rec2020'] as const) {
        expect(hl.tokens.css(t.color, f), `${t.color} ${f}`).toBe(t[f]);
      }
      expect(hl.tokens.android(t.color)).toBe(t.android);
      expect(hl.tokens.iosP3(t.color)).toEqual(t.ios_p3);
      expect(hl.tokens.swift(t.color)).toBe(t.swift);
    }
    expect(hl.tokens.cssVariables(hl.gen.scale('#3b82f6'), '--primary')).toBe(ref.css_variables);
  });

  it('JS round-trip precision matches Python (0 hex misses on same grid)', () => {
    const N = ref.grid_n;
    const step = Math.floor(255 / (N - 1)) || 1;
    const levels: number[] = [];
    for (let v = 0; v <= 255 && levels.length < N; v += step) levels.push(v);
    let genMiss = 0, metMiss = 0;
    const hx = (v: number) => v.toString(16).padStart(2, '0');
    for (const r of levels) for (const g of levels) for (const b of levels) {
      const h = `#${hx(r)}${hx(g)}${hx(b)}`;
      if (hl.gen.toHex(hl.gen.fromHex(h)) !== h) genMiss++;
      if (hl.metric.toHex(hl.metric.fromHex(h)) !== h) metMiss++;
    }
    expect(genMiss).toBe(ref.py_roundtrip.gen_hex_misses);   // 0
    expect(metMiss).toBe(ref.py_roundtrip.metric_hex_misses); // 0
  });

  it('REPORT: worst diffs per category', () => {
    const lines = Object.entries(worst).sort().map(([k, v]) => `  ${k}: ${v.toExponential(2)}`);
    console.log('\n═══ Py↔JS worst-case diffs ═══\n' + lines.join('\n'));
    expect(true).toBe(true);
  });
});
