/**
 * SINGLE SOURCE OF TRUTH for every factual claim on the site.
 *
 * Rule: components and pages must NEVER hardcode a number. Read base numbers
 * from `claims`, and compute derived values (percentages, multipliers, the
 * win record) with the helper functions below. This makes "62 vs 64 vs 65",
 * "30% vs 43%", etc. structurally impossible — there is one number, computed
 * one way, everywhere.
 *
 * The ColorBench-derived block (record, categories, gradient metrics) is
 * regenerated by `scripts/generate_claims.py` from the canonical result JSONs,
 * so re-running ColorBench updates the whole site. STRESS + package facts are
 * measured separately and validated in landing/SITE_CLAIMS_AUDIT.md.
 */
import { VERSION } from './version';

export const claims = {
  version: VERSION,

  // ── Generation: ColorBench head-to-head vs OKLab (fresh same-code run) ──
  // genspace + oklab + ties === total. Per-category sums equal the record.
  record: { genspace: 62, oklab: 9, ties: 19, total: 90 },
  categories: [
    { name: 'Gamut',         genspace: 24, oklab: 0, ties: 3 },
    { name: 'Application',   genspace: 8, oklab: 1, ties: 3 },
    { name: 'Independent',   genspace: 6, oklab: 1, ties: 0 },
    { name: 'Gradient',      genspace: 5, oklab: 3, ties: 3 },
    { name: 'Perceptual',    genspace: 5, oklab: 0, ties: 0 },
    { name: 'Structural',    genspace: 4, oklab: 2, ties: 2 },
    { name: 'Achromatic',    genspace: 2, oklab: 0, ties: 0 },
    { name: 'Advanced',      genspace: 2, oklab: 0, ties: 4 },
    { name: 'Hue',           genspace: 2, oklab: 0, ties: 0 },
    { name: 'Special',       genspace: 2, oklab: 1, ties: 0 },
    { name: 'Accessibility', genspace: 1, oklab: 1, ties: 0 },
    { name: 'Banding',       genspace: 1, oklab: 0, ties: 1 },
    { name: 'Numerical',     genspace: 0, oklab: 0, ties: 3 },
  ],
  internalMetrics: 83,
  independentMetrics: 7,
  gradientPairs: 3038,

  // ── Generation: headline gradient/gamut metrics (oklab vs genspace) ──
  cusps: {
    sRGB:    { genspace: 360, oklab: 299, total: 360 },
    P3:      { genspace: 360, oklab: 308, total: 360 },
    Rec2020: { genspace: 360, oklab: 360, total: 360 },
  },
  monotonicity:    { sRGB: 0, P3: 0, Rec2020: 1 },
  oklabP3MonoViol: 71,
  roundtrip: {
    sRGB:    { genspace: 5.64e-8,  oklab: 1.67e-15 },
    P3:      { genspace: 2.0e-15,  oklab: 1.67e-15 },
    Rec2020: { genspace: 1.78e-15, oklab: 1.55e-15 },
  },
  achromaticCstar: { genspace: 1.88e-15, oklab: 7.61e-7 },
  munsellValueCV:  { genspace: 0.156, oklab: 2.797 },   // % (dL_cv)
  blueWhiteGR:     { genspace: 1.513, oklab: 1.408 },
  cuspSmoothness:  { genspace: 0.072, oklab: 0.805 },
  yellowChroma:    { genspace: 0.333, oklab: 0.211 },
  hueDriftMax:     { genspace: 77.5, oklab: 112.7 },     // degrees
  hungBernsMad:    { genspace: 4.716, oklab: 4.959 },    // degrees
  hueAgreementVsCieLab: 8.3,                             // degrees (genspace)
  // Where OKLab wins — stated honestly, single source for the % both ways:
  deutanStep:      { genspace: 0.110, oklab: 0.157 },    // OKLab better
  nearAchromCV:    { genspace: 106.73, oklab: 85.95 },   // OKLab better
  darkGradientCV:  { genspace: 37.24, oklab: 47.28 },    // genspace better
  frameToFrameCV:  { genspace: 60.1, oklab: 62.1 },

  // ── Measurement: STRESS on COMBVD / MacAdam / Human Feedback ──
  // (with Bradford CAT; lower is better)
  stress: {
    metricSpace: { combvd: 22.48, macadam: 19.51, humanFeedback: 23.26, average: 21.75 },
    ciede2000:   { combvd: 29.20, macadam: 22.13, humanFeedback: 62.54, average: 37.96 },
    cie94:       { combvd: 33.37, macadam: 19.78, humanFeedback: 59.75, average: 37.63 },
    cam16ucs:    { combvd: 33.47, macadam: 18.71, humanFeedback: 58.02, average: 36.73 },
    ciecam02ucs: { combvd: 30.90, macadam: 19.21, humanFeedback: 57.83, average: 35.98 },
    oklab:       { combvd: 47.35, macadam: 32.72, humanFeedback: 57.27, average: 45.78 },
  },
  // Honest training/overfit facts (MetricSpace trained on COMBVD only;
  // MacAdam + Human Feedback are HELD-OUT, never trained on).
  overfit: { trainStress: 22.14, testStress: 23.91, crossValidated: 24.3, gap: 1.77, trainPairs: 3050, testPairs: 763 },
  bestMacadam: 'cam16ucs',   // CAM16-UCS (18.71) edges MetricSpace (19.51) on MacAdam — NOT a clean sweep

  // ── Datasets ──
  datasets: { combvdPairs: 3813, combvdSubsets: 6, macadamPairs: 128, humanFeedbackPairs: 3552 },

  // ── Package facts ──
  bundleKB: 16.9,            // minified + gzipped (measured: npm run size)
  oklabBundleKB: 2,
  metricParams: 72,
  genParams: 35,
  license: 'MIT',
  depcubicAlpha: 0.021,
  chromaPower: 0.978,

  // ── Externally-verified (NOT machine-checkable — confirm before trusting) ──
  external: {
    colorjsMerged: true,            // helmgen / helmgenlch / helmlab-metric on color-js master
    colorjsPublishedVersion: '0.6.1',
    arxivId: '2602.23010',          // ⚠ UNVERIFIED — confirm or remove
    humanJudgments: '64,000+',      // ⚠ UNSOURCED — confirm or remove
    repo: 'github.com/Grkmyldz148/helmlab',
  },
} as const;

// ── Derived helpers — compute, never store ──────────────────────────────

/** "62-9-19" */
export const recordStr = () => `${claims.record.genspace}-${claims.record.oklab}-${claims.record.ties}`;
/** "62-9" */
export const winShort = () => `${claims.record.genspace}-${claims.record.oklab}`;
/** total scored comparisons (90) */
export const totalMetrics = () => claims.record.genspace + claims.record.oklab + claims.record.ties;
/** "6-1" on the Independent category */
export const independentStr = () => {
  const c = claims.categories.find((x) => x.name === 'Independent')!;
  return `${c.genspace}-${c.oklab}`;
};

/** % improvement when LOWER is better (e.g. STRESS): pctLower(22.48, 29.20) → 23 */
export const pctLower = (better: number, worse: number) => Math.round((1 - better / worse) * 100);
/** % gain of a over b when HIGHER is better: pctGain(0.333, 0.211) → 58 */
export const pctGain = (a: number, b: number) => Math.round((a / b - 1) * 100);
/** integer multiplier: mult(2.797, 0.156) → 18 */
export const mult = (a: number, b: number) => Math.round(a / b);

// Named derived figures (one definition each — used across the site):
export const ciede2000ImprovementPct = () => pctLower(claims.stress.metricSpace.combvd, claims.stress.ciede2000.combvd);          // 23
export const humanFeedbackImprovementPct = () => pctLower(claims.stress.metricSpace.humanFeedback, claims.stress.ciede2000.humanFeedback); // 63
export const munsellMult = () => mult(claims.munsellValueCV.oklab, claims.munsellValueCV.genspace);                                // 18
export const cuspSmoothMult = () => mult(claims.cuspSmoothness.oklab, claims.cuspSmoothness.genspace);                             // 11
export const yellowChromaPct = () => pctGain(claims.yellowChroma.genspace, claims.yellowChroma.oklab);                            // 58
export const hueDriftReductionPct = () => pctLower(claims.hueDriftMax.genspace, claims.hueDriftMax.oklab);                        // 31
export const darkGradientPct = () => pctLower(claims.darkGradientCV.genspace, claims.darkGradientCV.oklab);                       // 21
// Where OKLab wins — ONE canonical framing (OKLab's advantage, gain over genspace):
export const oklabDeutanAdvantagePct = () => pctGain(claims.deutanStep.oklab, claims.deutanStep.genspace);                        // 43
export const oklabNearAchromAdvantagePct = () => pctLower(claims.nearAchromCV.oklab, claims.nearAchromCV.genspace);               // 19
export const bundleRatio = () => Math.round(claims.bundleKB / claims.oklabBundleKB);                                              // 8
